name: Deploy to Amazon Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm i
    - name: build an executable file
      run: npm run build
    - name: make a zip file
      run: zip dist.zip dist/index.js
    - name: configure an aws cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-2
    - name: deploy aws lambda
      run: aws lambda update-function-code --function-name=test-lmd --zip-file fileb://dist.zip
