name: Deploy to Amazon Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm i
    - name: build an executable file
      run: npm run build
    - run: cp -R ./node_modules ./build/node_modules
    - name: make a zip file
      run: cd dist && zip ../dist.zip .
    - name: configure an aws cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
    - name: deploy aws lambda
      run: aws lambda update-function-code --function-name=test-lmd --zip-file fileb://dist.zip
    - name: build an executable file for migration lambda
      run: npm run build-migration
    - run: cp -R ./node_modules ./build/node_modules
    - name: make a zip file
      run: cd dist && zip ../dist.zip .
    - name: deploy aws lambda for migration
      run: aws lambda update-function-code --function-name=migrations --zip-file fileb://dist.zip
    - name: invoke second aws lambda to run migration
      run: aws lambda invoke --function-name=migrations res.json
    - name: result of second aws lambda invoke
      run: cat res.json
